language: python

python:
    - "2.7"
    - "3.5"


env:
- TOXENV=py27-d18
- TOXENV=py27-d19
- TOXENV=py27-d110
- TOXENV=py35-d18
- TOXENV=py35-d19
- TOXENV=py35-d110
- TOXENV=cov

branches:
    only:
    - master
    - develop

install: pip install --quiet --use-mirrors tox tox-travis

script: tox

after_script:
- if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
  fi
